name: Helm Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
          charts-folder: helm-charts/health-patterns